- group: core
  key: redis
  name: Redis
  value_type: yaml
  value: "addr: redis:6379\r\npassword:  \"\"\r\ndb: 1"
- group: knowledge
  key: redis
  name: Redis
  value_type: yaml
  value: "addr: redis:6379\r\npassword: \"\"\r\ndb: 4\r\n"
- group: core
  key: cos-ke
  name: knowlegde存储
  value_type: yaml
  value: "purpose: forest-file\r\npresigned_timeout: \"24h\"\r\ns3:\r\n  end_point: {{ .Values.env.BASE_URL }}\r\n  access_key_id: {{ .Values.minio.username }}\r\n  secret_access_key: {{ .Values.minio.password }}\r\n  region: minio\r\n  bucket: corekg-bucket\r\n  use_path_style: true\r\n\r\n"
- group: knowledge
  key: es
  name: es配置
  value_type: yaml
  value: "addresses:\r\n  - http://127.0.0.1:9200\r\nusername: elastic\r\nmax_retries: 3\r\nslow_threshold: 3s"
- group: knowledge
  key: llm_image_parse
  name: llm_image_parse
  value_type: yaml
  value: "api_key: {{ .Values.env.LLM_VL_MODEL_APIKEY }}\r\nbase_url: {{ .Values.env.LLM_VL_MODEL_URL }}/chat/completions\r\nmodel_name: \"{{ .Values.env.LLM_VL_MODEL }}\""
- group: knowledge
  key: nebula
  name: 图数据库配置
  value_type: yaml
  value: "address: \"nebula-graphd-0.nebula-graphd\"\r\nport: 9669\r\nusername: \"root\"\r\npassword: \"nebula\"\r\nprefix: \"know\""
- group: knowledge
  key: embedding
  name: embedding模型配置
  value_type: yaml
  value: "url: {{ .Values.env.LLM_EMBEDDING_MODEL_URL }}/embeddings\r\nkey: \"{{ .Values.env.LLM_EMBEDDING_MODEL_APIKEY }}\"\r\nmodel_name: \"{{ .Values.env.LLM_EMBEDDING_MODEL_NAME }}\""
- group: knowledge
  key: convert_pdf
  name: 文件转PDF
  value_type: yaml
  value: "default:\n  url: \"http://word2pdf:3000/forms/libreoffice/convert\"\n  api_key: \"\"\n  file_field: \"files\"\n  response_is_file: true\n  file_url_field: \"\"\nofd:\n  url: \"http://word2pdf:3000/forms/ofd/convert\"\n  api_key: \"\"\n  file_field: \"file\"\n  response_is_file: false\n  file_url_field: \"response.pdf_url\""
- group: core
  key: cos-cu-image
  name: account头像存储
  value_type: yaml
  value: "purpose: cu-image\r\npresigned_timeout: \"24h\"\r\ns3:\r\n  end_point: {{ .Values.env.BASE_URL }}\r\n  access_key_id: {{ .Values.minio.username }}\r\n  secret_access_key: {{ .Values.minio.password }}\r\n  region: minio\r\n  bucket: corekg-bucket\r\n  use_path_style: true\r\n\r\n"
- group: core
  key: cos-yg-chat
  name: 轻应用头像存储
  value_type: yaml
  value: "purpose: yg-chat\r\npresigned_timeout: \"24h\"\r\ns3:\r\n  end_point: {{ .Values.env.BASE_URL }}\r\n  access_key_id: {{ .Values.minio.username }}\r\n  secret_access_key: {{ .Values.minio.password }}\r\n  region: minio\r\n  bucket: corekg-bucket\r\n  use_path_style: true\r\n\r\n"
- group: knowledge
  key: mysql_excel_instance
  name: excel问答 mysql 实例信息
  value_type: yaml
  value: "host: mysql\nport: 3306\r\nusername: root \r\npassword: {{ .Values.mysql.rootPassword }} \r\ncharset: utf8mb4\r\n"
- group: corekg
  key: license_public_key
  name: license_public_key
  value_type: text
  value: "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEA2yzBf3x0puJOadJpnvyqNR0RCRMC5TSUO1EnY5SjDjtqHbap2Lkn\n96kkvcyT2sEY/Wr4/KwhkBRET5uZnvzEOQYiyQJIJbVtVQ+jjuUMiOih2PppWt34\n9ypLjhcbzAwanbUMM2kfsI8yPBem0fm6ewgKhJVOQWqG8p13+Jnr39a42vKh9M3Q\nIndbNOSEvdX77L+73n98UlIpgrkzj0383jHCXy3hTL61ZOjk8rqhGjTorq/LaQQt\nWyc1h8nyKDAnm6RX40BzzP+TiaZyW6sgmK0ugUcMSQMy4S542DgG/VnAayYLMCl3\nWMfu/sTo2IfTqfZrTDCpA9+5HcAb4ordHwIDAQAB\n-----END RSA PUBLIC KEY-----"
- group: knowledge
  key: highlight
  name: 搜索高亮配置
  value_type: yaml
  value: "highlight_prefix: \"<span style=\\\"background-color: #FFE819; color: #1E1F28; padding: 3px 6px; border-radius: 4px; font-size: 16px; font-weight: 400; box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.26); border: 1px solid #FFF275; font-family: PingFang SC;\\\">\"\r\nhighlight_suffix: \"</span>\""
- group: corekg
  key: coze_url
  name: coze地址
  value_type: text
  value: "{{ .Values.env.BASE_SCHEMA}}://{{ .Values.env.BASE_HOST}}:{{ .Values.coze.port}}"
- group: corekg
  key: coze_ip
  name: cozeIP
  value_type: text
  value: "{{ .Values.env.BASE_HOST}}"
- group: corekg
  key: corekg_url
  name: corekg地址
  value_type: text
  value: "{{ .Values.env.BASE_URL}}"
- group: account
  key: pkl_connect_providers
  name: 外部授权配置
  value_type: yaml
  value: "providers:\n  - name: gmail\n    logo: https://cdn.openpo.com/connect/gmail.svg\n    enable: true\n    method: oauth2\n    platform: google\n    client_id: \"CHANGE_ME_GOOGLE_CLIENT_ID\"\n    client_secret: \"CHANGE_ME_GOOGLE_CLIENT_SECRET\"\n    redirect_url: \"https://ai.example.com/v2/account.Connect/callback\"\n    scopes:\n      - openid\n      - email\n      - profile\n      - https://www.googleapis.com/auth/gmail.readonly\n\n  - name: google-drive\n    logo: https://cdn.openpo.com/connect/google-drive.svg\n    enable: true\n    method: oauth2\n    platform: google\n    client_id: \"CHANGE_ME_GOOGLE_CLIENT_ID\"\n    client_secret: \"CHANGE_ME_GOOGLE_CLIENT_SECRET\"\n    redirect_url: \"https://ai.example.com/v2/account.Connect/callback\"\n    scopes:\n      - openid\n      - email\n      - profile\n      - https://www.googleapis.com/auth/drive.readonly\n\n  - name: slack\n    logo: https://cdn.openpo.com/connect/slack.svg\n    enable: true\n    method: oauth2\n    platform: slack\n    client_id: \"CHANGE_ME_SLACK_CLIENT_ID\"\n    client_secret: \"CHANGE_ME_SLACK_CLIENT_SECRET\"\n    redirect_url: \"https://ai.example.com/v2/account.Connect/callback\"\n    scopes:\n      - channels:read\n      - groups:read\n      - im:read\n      - mpim:read\n      - channels:history\n      - groups:history\n      - im:history\n      - mpim:history\n      - users:read\n      - users:read.email\n\n  - name: confluence\n    logo: https://cdn.openpo.com/connect/confluence.svg\n    enable: true\n    method: oauth2\n    platform: confluence\n    client_id: \"CHANGE_ME_CONFLUENCE_CLIENT_ID\"\n    client_secret: \"CHANGE_ME_CONFLUENCE_CLIENT_SECRET\"\n    redirect_url: \"https://ai.example.com/v2/account.Connect/callback\"\n    scopes:\n      - read:content:confluence\n      - read:content-details:confluence\n      - read:label:confluence\n      - read:user:confluence\n      - read:space:confluence\n      - read:hierarchical-content:confluence\n      - read:content.metadata:confluence\n      - search:confluence\n      - read:me\n      - read:email-address:confluence"
- group: knowledge
  key: rerank
  name: rerank模型
  value_type: yaml
  value: "url: {{ .Values.env.LLM_RERANKER_URL}}\r\nkey: {{ .Values.env.LLM_RERANKER_KEY}}\r\nmodel_name: {{ .Values.env.LLM_RERANKER_MODEL_NAME}}"
- group: core
  key: cos-company-logo
  name: 公司头像存储
  value_type: yaml
  value: "purpose: company-logo\ns3:\n  end_point: http://localhost:9000\n  access_key_id: CHANGE_ME_S3_ACCESS_KEY\n  secret_access_key: CHANGE_ME_S3_SECRET_KEY\n  \nregion: cn-xian\n  bucket: test-knownow\n  use_path_style: true"
