// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplatecorekg = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/corekg.CheckLicense": {
            "post": {
                "description": "检查license状态",
                "tags": [
                    "license自助"
                ],
                "summary": "检查license状态",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apiobj.BaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apiobj.BaseResponse"
                        }
                    }
                }
            }
        },
        "/corekg.GetLicenseInfo": {
            "post": {
                "description": "获取license元信息",
                "tags": [
                    "license自助"
                ],
                "summary": "获取license元信息",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/licensectl.RegisterLicenseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apiobj.BaseResponse"
                        }
                    }
                }
            }
        },
        "/corekg.RegisterLicense": {
            "post": {
                "description": "注册license",
                "tags": [
                    "license自助"
                ],
                "summary": "注册license",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/licensectl.RegisterLicenseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apiobj.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apiobj.BaseRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "apiobj.BaseResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "licensectl.RegisterLicenseRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "company_logo": {
                            "type": "string"
                        },
                        "company_name": {
                            "type": "string"
                        },
                        "license": {
                            "type": "string"
                        },
                        "website_info": {
                            "$ref": "#/definitions/licensectl.WebsiteInfo"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "licensectl.WebsiteInfo": {
            "type": "object",
            "properties": {
                "website_logo": {
                    "type": "string"
                },
                "website_name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Description for what is this security definition being used",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfocorekg holds exported Swagger Info so clients can modify it
var SwaggerInfocorekg = &swag.Spec{
	Version:          "",
	Host:             "tapi.example.com",
	BasePath:         "/apis/p",
	Schemes:          []string{"http"},
	Title:            "kecore API",
	Description:      "doc.json",
	InfoInstanceName: "corekg",
	SwaggerTemplate:  docTemplatecorekg,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfocorekg.InstanceName(), SwaggerInfocorekg)
}
