// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agent_lwps.DeletePaperReview": {
            "post": {
                "description": "删除论文审阅",
                "tags": [
                    "Paper_Review 论文审阅"
                ],
                "summary": "删除论文审阅",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.DeletePaperReviewHistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.DeletePaperReviewHistoryResponse"
                        }
                    }
                }
            }
        },
        "/agent_lwps.ExportPaperReport": {
            "post": {
                "description": "导出盲审报告",
                "tags": [
                    "Paper_Review 论文审阅"
                ],
                "summary": "导出盲审报告",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ExportPaperReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ExportPaperReportResponse"
                        }
                    }
                }
            }
        },
        "/agent_lwps.GetReviewHistoryByID": {
            "post": {
                "description": "根据id获取论文评审历史记录",
                "tags": [
                    "Paper_Review 论文审阅"
                ],
                "summary": "get paper review history by id 根据id获取论文评审的详细信息",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.GetReviewHistoryByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.GetReviewHistoryByIDResponse"
                        }
                    }
                }
            }
        },
        "/agent_lwps.ListReviewHistory": {
            "post": {
                "description": "根据 uin 获取用户汇总历史信息",
                "tags": [
                    "Paper_Review 论文审阅"
                ],
                "summary": "get paper review history by uin 根据 uin 获取用户汇总历史信息",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ListReviewHistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ListReviewHistoryResponse"
                        }
                    }
                }
            }
        },
        "/agent_lwps.PreviewFile": {
            "post": {
                "description": "预览file",
                "tags": [
                    "Preview_File"
                ],
                "summary": "预览file",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.PreviewFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.PreviewFileResponse"
                        }
                    }
                }
            }
        },
        "/agent_lwps.ReviewPaper": {
            "post": {
                "description": "调用算法将pdf转化成markdown,之后调用评审算法，返回评审请求",
                "tags": [
                    "Paper_Review 论文审阅"
                ],
                "summary": "review paper 根据要求审阅上传的论文",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ReviewPaperRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ReviewPaperResponse"
                        }
                    }
                }
            }
        },
        "/agent_lwps.UploadFile": {
            "post": {
                "description": "上传file",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Upload_File"
                ],
                "summary": "上传file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "论文pdf文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "aiagents-file",
                        "description": "用途，固定值为 aiagents-file",
                        "name": "purpose",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.UploadFileResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "agentlwpstype.ExportType": {
            "type": "string",
            "enum": [
                "mangshen",
                "pingfen"
            ],
            "x-enum-varnames": [
                "ExportTypeMangshen",
                "ExportTypePingfen"
            ]
        },
        "agentlwpstype.PaperReviewHistory": {
            "type": "object",
            "properties": {
                "company_id": {
                    "description": "公司id",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "file_ext": {
                    "description": "FileExt 文件扩展名",
                    "type": "string"
                },
                "file_id": {
                    "description": "FileId 论文PDF文件id",
                    "type": "integer"
                },
                "grading_full": {
                    "description": "GradingFull 论文满分",
                    "allOf": [
                        {
                            "$ref": "#/definitions/agentlwpstype.StringMap"
                        }
                    ]
                },
                "grading_requirement": {
                    "description": "GradingRequirement 论文打分要求",
                    "allOf": [
                        {
                            "$ref": "#/definitions/agentlwpstype.StringMap"
                        }
                    ]
                },
                "grading_results": {
                    "description": "GradingResults 论文打分结果（结果）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/agentlwpstype.StringMap"
                        }
                    ]
                },
                "id": {
                    "type": "integer"
                },
                "know_type": {
                    "description": "KnowType 论文领域",
                    "type": "string"
                },
                "markdown_id": {
                    "description": "MarkDownID markdown文件id",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "paper_end": {
                    "description": "论文结束页数",
                    "type": "integer"
                },
                "paper_start": {
                    "description": "论文起始页数",
                    "type": "integer"
                },
                "review_requirement": {
                    "description": "ReviewRequirement 论文评审要求",
                    "allOf": [
                        {
                            "$ref": "#/definitions/agentlwpstype.StringMap"
                        }
                    ]
                },
                "review_status": {
                    "description": "ReviewStatus 论文审阅状态 ( pending / running / success / failed )",
                    "allOf": [
                        {
                            "$ref": "#/definitions/agentlwpstype.TaskStatus"
                        }
                    ]
                },
                "review_type": {
                    "description": "ReviewType 论文评审类型 student / teacher",
                    "allOf": [
                        {
                            "$ref": "#/definitions/agentlwpstype.ReviewType"
                        }
                    ]
                },
                "summarized_questions": {
                    "description": "SummarizedQuestions 论文存在的问题（结果）",
                    "type": "string"
                },
                "summarized_reviews": {
                    "description": "SummarizedReviews 论文评审意见（结果）",
                    "type": "string"
                },
                "uin": {
                    "description": "Uin 用户唯一标识",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "agentlwpstype.ReviewType": {
            "type": "string",
            "enum": [
                "student",
                "teacher"
            ],
            "x-enum-varnames": [
                "ReviewTypeStudent",
                "ReviewTypeTeacher"
            ]
        },
        "agentlwpstype.StringMap": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "agentlwpstype.TaskStatus": {
            "type": "string",
            "enum": [
                "pending",
                "success",
                "fail",
                "running"
            ],
            "x-enum-comments": {
                "TaskStatusParseFailed": "解析失败",
                "TaskStatusPending": "等待中",
                "TaskStatusSuccess": "已完成"
            },
            "x-enum-varnames": [
                "TaskStatusPending",
                "TaskStatusSuccess",
                "TaskStatusParseFailed",
                "TaskStatusParseRunning"
            ]
        },
        "apiobj.Filter": {
            "type": "object",
            "properties": {
                "exactMatch": {
                    "type": "boolean"
                },
                "field": {
                    "type": "string"
                },
                "value": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "apiobj.PageQuery": {
            "type": "object",
            "properties": {
                "beginTime": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "filters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apiobj.Filter"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "listAll": {
                    "type": "boolean"
                },
                "offset": {
                    "type": "integer"
                },
                "orderBy": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "apis.DeletePaperReviewHistoryRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "apis.DeletePaperReviewHistoryResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "apis.ExportPaperReportRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "type": {
                            "$ref": "#/definitions/agentlwpstype.ExportType"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "apis.ExportPaperReportResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "apis.FileInfo": {
            "type": "object",
            "properties": {
                "file_id": {
                    "type": "integer"
                },
                "filename": {
                    "description": "Filename 原始文件名",
                    "type": "string"
                },
                "uin": {
                    "type": "integer"
                },
                "url": {
                    "description": "URL 文件访问地址",
                    "type": "string"
                }
            }
        },
        "apis.GetReviewHistoryByIDRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "apis.GetReviewHistoryByIDResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "paper_review_history": {
                            "$ref": "#/definitions/agentlwpstype.PaperReviewHistory"
                        }
                    }
                }
            }
        },
        "apis.ListReviewHistoryRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/apiobj.PageQuery"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "apis.ListReviewHistoryResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/agentlwpstype.PaperReviewHistory"
                            }
                        },
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        },
                        "total": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.PreviewFileRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "apis.PreviewFileResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "apis.ReviewPaperRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "file_id": {
                            "type": "integer"
                        },
                        "grading_requirements": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "description": {
                                        "type": "string"
                                    },
                                    "score": {
                                        "type": "integer"
                                    }
                                }
                            }
                        },
                        "know_type": {
                            "type": "string"
                        },
                        "page_end": {
                            "type": "integer"
                        },
                        "page_start": {
                            "type": "integer"
                        },
                        "review_requirements": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "review_type": {
                            "$ref": "#/definitions/agentlwpstype.ReviewType"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "apis.ReviewPaperResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.UploadFileResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/apis.FileInfo"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Description for what is this security definition being used",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "47.92.112.152:8199",
	BasePath:         "/apis/p",
	Schemes:          []string{"http"},
	Title:            "chat API````````````",
	Description:      "doc.json",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
