// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplateketask = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Description for what is this security definition being used",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfoketask holds exported Swagger Info so clients can modify it
var SwaggerInfoketask = &swag.Spec{
	Version:          "",
	Host:             "47.92.112.152:8199",
	BasePath:         "/apis/p",
	Schemes:          []string{"http"},
	Title:            "ketask API````````````",
	Description:      "doc.json",
	InfoInstanceName: "ketask",
	SwaggerTemplate:  docTemplateketask,
}

func init() {
	swag.Register(SwaggerInfoketask.InstanceName(), SwaggerInfoketask)
}
