SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `ke_package` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL COMMENT '套餐名称',
  `description` varchar(512) DEFAULT NULL COMMENT '套餐描述',
  `price` bigint unsigned NOT NULL DEFAULT '0' COMMENT '价格（分）',
  `sale_price` bigint unsigned NOT NULL DEFAULT '0' COMMENT '售价（分）',
  `agent_quota` int unsigned NOT NULL DEFAULT '0' COMMENT '可创建智能体数量',
  `qa_quota` int unsigned NOT NULL DEFAULT '0' COMMENT '每日问答次数',
  `disk_quota` bigint unsigned NOT NULL DEFAULT '0' COMMENT '磁盘配额（字节）',
  `employee_quota` int unsigned NOT NULL DEFAULT '0' COMMENT '成员数量',
  `edition` varchar(16) NOT NULL DEFAULT 'professional' COMMENT '套餐类型，free_trail：免费版，professional：专业版',
  `level` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '套餐级别，数字越大级别越高',
  `period_type` varchar(16) NOT NULL DEFAULT 'month' COMMENT '会员周期类型，month：月度会员，year：年度会员，lifetime：永久会员',
  `source_type` varchar(16) NOT NULL DEFAULT 'manual' COMMENT '套餐来源，system：系统内置，manual：运营添加',
  `extra` text DEFAULT NULL COMMENT '扩展信息（JSON格式）',
  `status` varchar(16) NOT NULL DEFAULT 'draft' COMMENT '套餐状态：draft-草稿，online-上架，offline-下架',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` datetime(3) DEFAULT NULL COMMENT '删除时间, NULL表示未删除',
  PRIMARY KEY (`id`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='套餐表';

CREATE TABLE IF NOT EXISTS `sale_order` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `company_id` bigint unsigned NOT NULL COMMENT '公司ID',
  `uin` bigint unsigned NOT NULL COMMENT '购买人员ID（user_identification的ID）',
  `order_sn` varchar(64) NOT NULL COMMENT '订单号',
  `total_amount` bigint unsigned NOT NULL DEFAULT '0' COMMENT '订单总金额（分）',
  `payment_amount` bigint unsigned NOT NULL DEFAULT '0' COMMENT '支付金额（实付金额，分）',
  `payment_channel` varchar(32) DEFAULT NULL COMMENT '支付渠道：wechat-微信，alipay-支付宝，bank-银行转账等',
  `order_status` varchar(16) NOT NULL DEFAULT 'pending' COMMENT '订单状态：pending-待支付，success-已完成，closed-已关闭，cancelled-已取消',
  `business_source` varchar(32) DEFAULT NULL COMMENT '业务来源，knowledge：知识引擎',
  `business_type` varchar(32) DEFAULT NULL COMMENT '业务类型，例如 subscription：订阅付费、资源付费等类型，维护后期订单回调处理',
  `paid_at` datetime DEFAULT NULL COMMENT '成功支付时间',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` datetime(3) DEFAULT NULL COMMENT '删除时间, NULL表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `udx_order_sn` (`order_sn`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `idx_company_id` (`company_id`),
  KEY `idx_uin` (`uin`),
  KEY `idx_order_status` (`order_status`),
  KEY `idx_business_source` (`business_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单表';

CREATE TABLE IF NOT EXISTS `sale_order_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL COMMENT '订单ID',
  `product_id` bigint unsigned NOT NULL COMMENT '商品ID',
  `product_name` varchar(64) NOT NULL COMMENT '商品名称（冗余字段，便于查询）',
  `business_source` varchar(32) DEFAULT NULL COMMENT '业务来源，knowledge：知识引擎',
  `price` bigint unsigned NOT NULL DEFAULT '0' COMMENT '商品价格（分）',
  `quantity` int unsigned NOT NULL DEFAULT '1' COMMENT '购买数量',
  `total_amount` bigint unsigned NOT NULL DEFAULT '0' COMMENT '订单总金额（分）',
  `payment_amount` bigint unsigned NOT NULL DEFAULT '0' COMMENT '支付金额（实付金额，分）',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` datetime(3) DEFAULT NULL COMMENT '删除时间, NULL表示未删除',
  PRIMARY KEY (`id`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `idx_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单明细表';

CREATE TABLE IF NOT EXISTS `ke_company_quota` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `company_id` bigint unsigned NOT NULL COMMENT '公司ID',
  `source_type` varchar(16) NOT NULL COMMENT '配额来源：order-订单，manual-手动发放',
  `operator_id` bigint unsigned DEFAULT NULL COMMENT '操作人ID（手动发放时记录操作人）',
  `package_level` tinyint unsigned DEFAULT 1 COMMENT '套餐级别，数字越大级别越高',
  `agent_quota` int unsigned NOT NULL DEFAULT '0' COMMENT '可创建智能体数量',
  `qa_quota` int unsigned NOT NULL DEFAULT '0' COMMENT '每日问答次数',
  `disk_quota` bigint unsigned NOT NULL DEFAULT '0' COMMENT '磁盘配额（字节）',
  `employee_quota` int unsigned NOT NULL DEFAULT '0' COMMENT '成员数量',
  `effective_at` datetime(3) DEFAULT NULL COMMENT '生效时间',
  `expire_at` datetime(3) DEFAULT NULL COMMENT '过期时间',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` datetime(3) DEFAULT NULL COMMENT '删除时间, NULL表示未删除',
  PRIMARY KEY (`id`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `idx_company_id` (`company_id`),
  KEY `idx_operator_id` (`operator_id`),
  KEY `idx_expire_at` (`expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='公司配额表';

-- 支付记录表，公共服务中的表
CREATE TABLE IF NOT EXISTS `sale_payment_record` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL COMMENT '订单ID',
  `order_sn` varchar(64) DEFAULT NULL COMMENT '订单号（冗余字段，便于查询）',
  `company_id` bigint unsigned DEFAULT NULL COMMENT '公司ID（冗余字段，便于查询）',
  `uin` bigint unsigned DEFAULT NULL COMMENT '用户ID（冗余字段，便于查询）',
  `record_sn` varchar(64) NOT NULL COMMENT '支付记录号',
  `record_type` varchar(16) NOT NULL COMMENT '记录类型：payment-支付，refund-退款',
  `business_source` varchar(32) DEFAULT NULL COMMENT '业务来源，knowledge：知识引擎',
  `amount` bigint unsigned NOT NULL DEFAULT '0' COMMENT '金额（分）',
  `payment_channel` varchar(32) DEFAULT NULL COMMENT '支付渠道：alipay-支付宝，wechat-微信，bank-银行转账等',
  `trade_id` varchar(128) DEFAULT NULL COMMENT '三方交易ID',
  `trade_no` varchar(128) DEFAULT NULL COMMENT '三方交易号',
  `status` varchar(16) NOT NULL DEFAULT 'pending' COMMENT '流水状态：pending-处理中，success-成功，failed-失败',
  `paid_at` datetime(3) DEFAULT NULL COMMENT '支付时间',
  `request_params` text DEFAULT NULL COMMENT '调用三方入参（JSON格式）',
  `response_data` text DEFAULT NULL COMMENT '调用三方出参（JSON格式）',
  `callback_data` text DEFAULT NULL COMMENT '支付回调信息（JSON格式）：以最后一次回调内容为准',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` datetime(3) DEFAULT NULL COMMENT '删除时间, NULL表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `udx_record_sn` (`record_sn`),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_sn` (`order_sn`),
  KEY `idx_company_id` (`company_id`),
  KEY `idx_uin` (`uin`),
  KEY `idx_trade_id` (`trade_id`),
  KEY `idx_no` (`trade_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支付记录表';
