// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account.GetMyAction": {
            "post": {
                "description": "获取action_path列表",
                "tags": [
                    "运营个人中心"
                ],
                "summary": "获取action_path列表",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.GetMyActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.GetMyActionResponse"
                        }
                    }
                }
            }
        },
        "/admin.AddAPIKeyPrivilege": {
            "post": {
                "description": "添加API key权限",
                "tags": [
                    "API KEY 管理"
                ],
                "summary": "添加API key权限",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.AddAPIKeyPrivilegeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.AddAPIKeyPrivilegeResponse"
                        }
                    }
                }
            }
        },
        "/admin.CreatAPIKey": {
            "post": {
                "description": "创建API key",
                "tags": [
                    "API KEY 管理"
                ],
                "summary": "创建API key",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.CreatAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.CreatAPIKeyResponse"
                        }
                    }
                }
            }
        },
        "/admin.CreateEmployee": {
            "post": {
                "description": "添加员工",
                "tags": [
                    "运营员工"
                ],
                "summary": "添加员工",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.CreateEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.CreateEmployeeResponse"
                        }
                    }
                }
            }
        },
        "/admin.CreateLoginSetting": {
            "post": {
                "description": "创建登录页配置",
                "tags": [
                    "登录页配置管理"
                ],
                "summary": "创建登录页配置",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.CreateLoginSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.CreateLoginSettingResponse"
                        }
                    }
                }
            }
        },
        "/admin.CreateSetting": {
            "post": {
                "description": "新增配置",
                "tags": [
                    "配置管理"
                ],
                "summary": "新增配置",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.CreateSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.CreateSettingResponse"
                        }
                    }
                }
            }
        },
        "/admin.DeleteAPIKeyPrivilege": {
            "post": {
                "description": "删除API key权限",
                "tags": [
                    "API KEY 管理"
                ],
                "summary": "删除API key权限",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.DeleteAPIKeyPrivilegeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.DeleteAPIKeyPrivilegeResponse"
                        }
                    }
                }
            }
        },
        "/admin.DeleteEmployee": {
            "post": {
                "description": "删除用户",
                "tags": [
                    "账号管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.DeleteEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiobj.BaseResponse"
                        }
                    }
                }
            }
        },
        "/admin.DeleteLoginSetting": {
            "post": {
                "description": "删除登录页配置",
                "tags": [
                    "登录页配置管理"
                ],
                "summary": "删除登录页配置",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.DeleteLoginSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.DeleteLoginSettingResponse"
                        }
                    }
                }
            }
        },
        "/admin.GetEmployeeBindKey": {
            "post": {
                "description": "获取微信绑定bind_key参数",
                "tags": [
                    "运营员工"
                ],
                "summary": "获取微信绑定bind_key参数",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.GetEmployeeBindKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.GetEmployeeBindKeyResponse"
                        }
                    }
                }
            }
        },
        "/admin.GetLoginSettingByID": {
            "post": {
                "description": "根据ID获取登录页配置",
                "tags": [
                    "登录页配置管理"
                ],
                "summary": "根据ID获取登录页配置",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.GetLoginSettingByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.GetLoginSettingByIDResponse"
                        }
                    }
                }
            }
        },
        "/admin.ListAPIKey": {
            "post": {
                "description": "API key列表",
                "tags": [
                    "API KEY 管理"
                ],
                "summary": "API key列表",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ListAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ListAPIKeyResponse"
                        }
                    }
                }
            }
        },
        "/admin.ListAPIKeyPrivilege": {
            "post": {
                "description": "API Key 权限列表",
                "tags": [
                    "API KEY 管理"
                ],
                "summary": "API Key 权限列表",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ListAPIKeyPrivilegeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ListAPIKeyPrivilegeResponse"
                        }
                    }
                }
            }
        },
        "/admin.ListEmployee": {
            "post": {
                "description": "用户列表",
                "tags": [
                    "账号管理"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ListEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.ListEmployeeResponse"
                        }
                    }
                }
            }
        },
        "/admin.ListLoginSetting": {
            "post": {
                "description": "登录页配置列表",
                "tags": [
                    "登录页配置管理"
                ],
                "summary": "登录页配置列表",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ListLoginSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ListLoginSettingResponse"
                        }
                    }
                }
            }
        },
        "/admin.ListSetting": {
            "post": {
                "description": "配置列表",
                "tags": [
                    "配置管理"
                ],
                "summary": "配置列表",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ListSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ListSettingResponse"
                        }
                    }
                }
            }
        },
        "/admin.UpdateEmployee": {
            "post": {
                "description": "更新用户",
                "tags": [
                    "账号管理"
                ],
                "summary": "更新用户",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.UpdateEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apiobj.BaseResponse"
                        }
                    }
                }
            }
        },
        "/admin.UpdateLoginSetting": {
            "post": {
                "description": "修改登录页配置",
                "tags": [
                    "登录页配置管理"
                ],
                "summary": "修改登录页配置",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.UpdateLoginSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.UpdateLoginSettingResponse"
                        }
                    }
                }
            }
        },
        "/admin.UpdateSetting": {
            "post": {
                "description": "更改配置",
                "tags": [
                    "配置管理"
                ],
                "summary": "更改配置",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.UpdateSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.UpdateSettingResponse"
                        }
                    }
                }
            }
        },
        "/admin.UploadCustomerImage": {
            "post": {
                "description": "上位管理员图片",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Upload"
                ],
                "summary": "上位管理员图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.UploadImageResponse"
                        }
                    }
                }
            }
        },
        "/admin.UploadEmployeeImage": {
            "post": {
                "description": "上位用户图片",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Upload"
                ],
                "summary": "上位用户图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.UploadImageResponse"
                        }
                    }
                }
            }
        },
        "/llm.DeleteApiKey": {
            "post": {
                "description": "删除API key",
                "tags": [
                    "API KEY 管理"
                ],
                "summary": "删除API key",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.DeleteAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.DeleteAPIKeyResponse"
                        }
                    }
                }
            }
        },
        "/op.ChangeMyWechat": {
            "post": {
                "description": "换绑微信",
                "tags": [
                    "运营个人中心"
                ],
                "summary": "换绑微信",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ChangeMyWechatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ChangeMyWechatResponse"
                        }
                    }
                }
            }
        },
        "/op.CreatePosition": {
            "post": {
                "description": "添加职位",
                "tags": [
                    "运营职位权限"
                ],
                "summary": "添加职位",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.CreatePositionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.CreatePositionResponse"
                        }
                    }
                }
            }
        },
        "/op.CreatePrivilege": {
            "post": {
                "description": "添加权限",
                "tags": [
                    "运营权限"
                ],
                "summary": "添加权限",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.CreatePrivilegeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.CreatePrivilegeResponse"
                        }
                    }
                }
            }
        },
        "/op.DeletePosition": {
            "post": {
                "description": "删除职位",
                "tags": [
                    "运营职位权限"
                ],
                "summary": "删除职位",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.DeletePositionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.DeletePositionResponse"
                        }
                    }
                }
            }
        },
        "/op.DeletePrivilege": {
            "post": {
                "description": "删除权限",
                "tags": [
                    "运营权限"
                ],
                "summary": "删除权限",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.DeletePrivilegeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.DeletePrivilegeResponse"
                        }
                    }
                }
            }
        },
        "/op.GetMyUserInfo": {
            "post": {
                "description": "获取个人信息",
                "tags": [
                    "运营个人中心"
                ],
                "summary": "获取个人信息",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.GetMyUserInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.GetMyUserInfoResponse"
                        }
                    }
                }
            }
        },
        "/op.GetPositionDetail": {
            "post": {
                "description": "职位详情",
                "tags": [
                    "运营职位权限"
                ],
                "summary": "职位详情",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.GetPositionDetailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.GetPositionDetailResponse"
                        }
                    }
                }
            }
        },
        "/op.ListPosition": {
            "post": {
                "description": "职位列表",
                "tags": [
                    "运营职位权限"
                ],
                "summary": "职位列表",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ListPositionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ListPositionResponse"
                        }
                    }
                }
            }
        },
        "/op.ListPrivilege": {
            "post": {
                "description": "权限列表",
                "tags": [
                    "运营权限"
                ],
                "summary": "权限列表",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ListPrivilegeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ListPrivilegeResponse"
                        }
                    }
                }
            }
        },
        "/op.ModifyMyUserInfo": {
            "post": {
                "description": "编辑个人信息",
                "tags": [
                    "运营个人中心"
                ],
                "summary": "编辑个人信息",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ModifyMyUserInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ModifyMyUserInfoResponse"
                        }
                    }
                }
            }
        },
        "/op.ModifyPositionInfo": {
            "post": {
                "description": "修改职位基本信息",
                "tags": [
                    "运营职位权限"
                ],
                "summary": "修改职位基本信息",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ModifyPositionInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ModifyPositionInfoResponse"
                        }
                    }
                }
            }
        },
        "/op.ModifyPositionPrivilege": {
            "post": {
                "description": "修改职位权限信息",
                "tags": [
                    "运营职位权限"
                ],
                "summary": "修改职位权限信息",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ModifyPositionPrivilegeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ModifyPositionPrivilegeResponse"
                        }
                    }
                }
            }
        },
        "/op.ModifyPrivilege": {
            "post": {
                "description": "修改权限信息",
                "tags": [
                    "运营权限"
                ],
                "summary": "修改权限信息",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ModifyPrivilegeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/apis.ModifyPrivilegeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admintype.APIKey": {
            "type": "object",
            "properties": {
                "api_key": {
                    "description": "Key 密钥",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator_id": {
                    "description": "CreatorID 创建者ID",
                    "type": "integer"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "Name Key名称",
                    "type": "string"
                },
                "purpose": {
                    "description": "purpose 用途",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "admintype.Position": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "admintype.Privilege": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "action_path": {
                    "type": "string"
                },
                "api": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "description": "Name        string ` + "`" + `gorm:\"column:name;type:varchar(32);not null;default:'';comment:'姓名'\" json:\"name\"` + "`" + `",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "parent_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "admintype.SysRole": {
            "type": "string",
            "enum": [
                "sys_admin"
            ],
            "x-enum-varnames": [
                "SysRoleSysAdmin"
            ]
        },
        "admintype.UserGender": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "UserGenderUnspecified",
                "UserGenderMale",
                "UserGenderFemale"
            ]
        },
        "admintype.UserStatus": {
            "type": "string",
            "enum": [
                "normal",
                "disabled"
            ],
            "x-enum-varnames": [
                "UserStatusNormal",
                "UserStatusDisabled"
            ]
        },
        "apiobj.BaseResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "apiobj.Filter": {
            "type": "object",
            "properties": {
                "exactMatch": {
                    "type": "boolean"
                },
                "field": {
                    "type": "string"
                },
                "value": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "apiobj.PageQuery": {
            "type": "object",
            "properties": {
                "begin_time": {
                    "type": "integer"
                },
                "business_id": {
                    "description": "BusinessID 业务ID",
                    "type": "integer"
                },
                "cluster_uid": {
                    "description": "Cluster_UID 集群UID",
                    "type": "string"
                },
                "count": {
                    "description": "TOOD removed",
                    "type": "integer"
                },
                "end_time": {
                    "type": "integer"
                },
                "filters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apiobj.Filter"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "listAll": {
                    "type": "boolean"
                },
                "offset": {
                    "type": "integer"
                },
                "orderBy": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sort": {
                    "type": "string"
                }
            }
        },
        "apikey.ListAPIKeyPrivilege": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "action_path": {
                    "type": "string"
                },
                "api": {
                    "type": "string"
                },
                "api_id": {
                    "type": "integer"
                },
                "api_key_id": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "apikey.QueryListAPIKeyPrivilegeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apikey.ListAPIKeyPrivilege"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "apikey.QueryListAPIKeyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admintype.APIKey"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "apis.AddAPIKeyPrivilegeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "privilege_ids": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "apis.AddAPIKeyPrivilegeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object"
                }
            }
        },
        "apis.ChangeMyWechatRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "apis.ChangeMyWechatResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "apis.CreatAPIKeyRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "purpose": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "apis.CreatAPIKeyResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object"
                }
            }
        },
        "apis.CreateEmployeeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/employee.CreateEmployeeItem"
                }
            }
        },
        "apis.CreateEmployeeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "bind_key": {
                            "type": "string"
                        },
                        "employee_id": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.CreateLoginSettingRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/login_setting.LoginSetting"
                }
            }
        },
        "apis.CreateLoginSettingResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "apis.CreatePositionRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/employee.CreatePositionOption"
                }
            }
        },
        "apis.CreatePositionResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/admintype.Position"
                }
            }
        },
        "apis.CreatePrivilegeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/admintype.Privilege"
                }
            }
        },
        "apis.CreatePrivilegeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/admintype.Privilege"
                }
            }
        },
        "apis.CreateSettingRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/settings.SettingItem"
                }
            }
        },
        "apis.CreateSettingResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object"
                }
            }
        },
        "apis.DeleteAPIKeyPrivilegeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "key_id": {
                            "type": "integer"
                        },
                        "privilege_ids": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "apis.DeleteAPIKeyPrivilegeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object"
                }
            }
        },
        "apis.DeleteAPIKeyRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.DeleteAPIKeyResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object"
                }
            }
        },
        "apis.DeleteEmployeeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "delete_reason": {
                            "description": "DeleteReason 删除原因",
                            "type": "string"
                        },
                        "employee_id": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.DeleteLoginSettingRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/login_setting.LoginSetting"
                }
            }
        },
        "apis.DeleteLoginSettingResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "apis.DeletePositionRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.DeletePositionResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "apis.DeletePrivilegeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.DeletePrivilegeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "apis.FileInfo": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "integer"
                },
                "file_id": {
                    "type": "integer"
                },
                "filename": {
                    "description": "Filename 原始文件名",
                    "type": "string"
                },
                "uin": {
                    "type": "integer"
                },
                "url": {
                    "description": "URL 文件访问地址",
                    "type": "string"
                }
            }
        },
        "apis.GetEmployeeBindKeyRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.GetEmployeeBindKeyResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "bind_key": {
                            "type": "string"
                        },
                        "employee_id": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.GetLoginSettingByIDRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.GetLoginSettingByIDResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "loginSetting": {
                            "$ref": "#/definitions/login_setting.LoginSetting"
                        }
                    }
                }
            }
        },
        "apis.GetMyActionRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                }
            }
        },
        "apis.GetMyActionResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "action_paths": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "apis.GetMyUserInfoRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                }
            }
        },
        "apis.GetMyUserInfoResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "action_paths": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "avatar_url": {
                            "type": "string"
                        },
                        "createdAt": {
                            "type": "string"
                        },
                        "deletedAt": {
                            "$ref": "#/definitions/gorm.DeletedAt"
                        },
                        "email": {
                            "type": "string"
                        },
                        "gender": {
                            "$ref": "#/definitions/admintype.UserGender"
                        },
                        "id": {
                            "type": "integer"
                        },
                        "mobile": {
                            "type": "string"
                        },
                        "nick_name": {
                            "description": "NickName 微信昵称",
                            "type": "string"
                        },
                        "password": {
                            "type": "string"
                        },
                        "positions": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/admintype.Position"
                            }
                        },
                        "real_name": {
                            "description": "RealName 真实姓名",
                            "type": "string"
                        },
                        "realname_pinyin": {
                            "type": "string"
                        },
                        "status": {
                            "$ref": "#/definitions/admintype.UserStatus"
                        },
                        "sys_role": {
                            "$ref": "#/definitions/admintype.SysRole"
                        },
                        "uin": {
                            "description": "Uin 员工唯一ID",
                            "type": "integer"
                        },
                        "union_id": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string"
                        },
                        "username": {
                            "description": "Username 用户名，用于登录、显示，唯一，不可修改",
                            "type": "string"
                        },
                        "web_open_id": {
                            "type": "string"
                        },
                        "wecom_user_id": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "apis.GetPositionDetailRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "apis.GetPositionDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/employee.PositionDetail"
                }
            }
        },
        "apis.ListAPIKeyPrivilegeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "begin_time": {
                            "type": "integer"
                        },
                        "business_id": {
                            "description": "BusinessID 业务ID",
                            "type": "integer"
                        },
                        "cluster_uid": {
                            "description": "Cluster_UID 集群UID",
                            "type": "string"
                        },
                        "count": {
                            "description": "TOOD removed",
                            "type": "integer"
                        },
                        "end_time": {
                            "type": "integer"
                        },
                        "filters": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/apiobj.Filter"
                            }
                        },
                        "id": {
                            "type": "integer"
                        },
                        "limit": {
                            "type": "integer"
                        },
                        "listAll": {
                            "type": "boolean"
                        },
                        "offset": {
                            "type": "integer"
                        },
                        "orderBy": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "sort": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "apis.ListAPIKeyPrivilegeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/apikey.QueryListAPIKeyPrivilegeResponse"
                }
            }
        },
        "apis.ListAPIKeyRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/apiobj.PageQuery"
                }
            }
        },
        "apis.ListAPIKeyResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/apikey.QueryListAPIKeyResponse"
                }
            }
        },
        "apis.ListEmployeeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/apiobj.PageQuery"
                }
            }
        },
        "apis.ListEmployeeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/employee.EmployeeInfoItemList"
                }
            }
        },
        "apis.ListLoginSettingRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/apiobj.PageQuery"
                }
            }
        },
        "apis.ListLoginSettingResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/login_setting.QueryLoginSettingListResponse"
                }
            }
        },
        "apis.ListPositionRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/apiobj.PageQuery"
                }
            }
        },
        "apis.ListPositionResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/employee.QueryPositionListResponse"
                }
            }
        },
        "apis.ListPrivilegeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/apiobj.PageQuery"
                }
            }
        },
        "apis.ListPrivilegeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/employee.QueryPrivilegeListResponse"
                }
            }
        },
        "apis.ListSettingRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/apiobj.PageQuery"
                }
            }
        },
        "apis.ListSettingResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/employee.QuerySettingListResponse"
                }
            }
        },
        "apis.ModifyMyUserInfoRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/employee.EmployeeSimpleInfo"
                }
            }
        },
        "apis.ModifyMyUserInfoResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "apis.ModifyPositionInfoRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "createdAt": {
                            "type": "string"
                        },
                        "deletedAt": {
                            "$ref": "#/definitions/gorm.DeletedAt"
                        },
                        "description": {
                            "type": "string"
                        },
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "apis.ModifyPositionInfoResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/admintype.Position"
                }
            }
        },
        "apis.ModifyPositionPrivilegeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "privilege_ids": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "apis.ModifyPositionPrivilegeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/admintype.Position"
                }
            }
        },
        "apis.ModifyPrivilegeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "action": {
                            "type": "string"
                        },
                        "action_path": {
                            "type": "string"
                        },
                        "api": {
                            "type": "string"
                        },
                        "createdAt": {
                            "type": "string"
                        },
                        "deletedAt": {
                            "$ref": "#/definitions/gorm.DeletedAt"
                        },
                        "description": {
                            "description": "Name        string ` + "`" + `gorm:\"column:name;type:varchar(32);not null;default:'';comment:'姓名'\" json:\"name\"` + "`" + `",
                            "type": "string"
                        },
                        "id": {
                            "type": "integer"
                        },
                        "parent_id": {
                            "type": "integer"
                        },
                        "type": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "apis.ModifyPrivilegeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/admintype.Privilege"
                }
            }
        },
        "apis.UpdateEmployeeRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/employee.UpdateEmployeeItem"
                }
            }
        },
        "apis.UpdateLoginSettingRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/login_setting.LoginSetting"
                }
            }
        },
        "apis.UpdateLoginSettingResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "apis.UpdateSettingRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "default": {
                            "type": "string"
                        },
                        "describe": {
                            "type": "string"
                        },
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        },
                        "value_type": {
                            "$ref": "#/definitions/settings.ValueType"
                        }
                    }
                }
            }
        },
        "apis.UpdateSettingResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "apis.UploadImageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/apis.FileInfo"
                }
            }
        },
        "employee.CreateEmployeeItem": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/admintype.UserGender"
                },
                "phone": {
                    "type": "string"
                },
                "position_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "real_name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "employee.CreatePositionOption": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "privilege_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "employee.EmployeeInfoItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mobile": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                },
                "real_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "union_id": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "employee.EmployeeInfoItemList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/employee.EmployeeInfoItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "employee.EmployeeSimpleInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "employee.PositionDetail": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "privilege_ids": {
                    "description": "Privileges   []*admintype.Privilege ` + "`" + `json:\"privileges\"` + "`" + `",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "employee.PositionListItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "employee.QueryPositionListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/employee.PositionListItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "employee.QueryPrivilegeListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admintype.Privilege"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "employee.QuerySettingListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/settings.SettingItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "employee.UpdateEmployeeItem": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "gender": {
                    "$ref": "#/definitions/admintype.UserGender"
                },
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "position_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "real_name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "login_setting.EnvType": {
            "type": "string",
            "enum": [
                "test",
                "prod"
            ],
            "x-enum-varnames": [
                "EnvTest",
                "EnvProd"
            ]
        },
        "login_setting.LoginSetting": {
            "type": "object",
            "properties": {
                "agentid": {
                    "description": "企微agentid，自建项目使用",
                    "type": "string"
                },
                "allow_register": {
                    "description": "运行注册",
                    "type": "boolean"
                },
                "appid": {
                    "description": "微信登录appid",
                    "type": "string"
                },
                "appid_com": {
                    "description": "企微登录appid",
                    "type": "string"
                },
                "auth_key": {
                    "description": "key",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "domain_name": {
                    "description": "DomainName 域名",
                    "type": "string"
                },
                "env": {
                    "description": "Env 环境",
                    "allOf": [
                        {
                            "$ref": "#/definitions/login_setting.EnvType"
                        }
                    ]
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "description": "ImageUrl 图片链接",
                    "type": "string"
                },
                "is_enable_email": {
                    "type": "boolean"
                },
                "is_enable_phone": {
                    "type": "boolean"
                },
                "is_enable_wechat": {
                    "description": "// Methods 登录方式\nMethods []Method ` + "`" + `gorm:\"type:text;not null;serializer:json\" json:\"methods\"` + "`" + `",
                    "type": "boolean"
                },
                "is_enable_wechatcom": {
                    "type": "boolean"
                },
                "issuer": {
                    "description": "签发人信息",
                    "type": "string"
                },
                "path": {
                    "description": "Path 路径",
                    "type": "string"
                },
                "title": {
                    "description": "Title 标题",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "login_setting.QueryLoginSettingListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/login_setting.LoginSetting"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "settings.SettingItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "default": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "describe": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "value_type": {
                    "$ref": "#/definitions/settings.ValueType"
                }
            }
        },
        "settings.ValueType": {
            "type": "string",
            "enum": [
                "secret",
                "password",
                "text",
                "int64",
                "bool",
                "json",
                "yaml"
            ],
            "x-enum-varnames": [
                "ValueSecret",
                "ValuePassword",
                "ValueText",
                "ValueInt64",
                "ValueBool",
                "ValueJSON",
                "ValueYaml"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Description for what is this security definition being used",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "47.92.112.152:8099",
	BasePath:         "/v2",
	Schemes:          []string{"https", "http"},
	Title:            "Roc API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
