// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplatekesearch = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/kesearch.DeleteChunk": {
            "post": {
                "description": "删除chunk",
                "tags": [
                    "chunk 管理"
                ],
                "summary": "删除chunk",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chunkctl.DeleteChunkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/chunkctl.DeleteChunkResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.DisableFileChunk": {
            "post": {
                "description": "设置文件chunk状态",
                "tags": [
                    "chunk 管理"
                ],
                "summary": "设置文件chunk状态",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chunkctl.DisableFileChunkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/chunkctl.DisableFileChunkResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.ForestSearch": {
            "post": {
                "description": "知识库搜索",
                "tags": [
                    "知识库搜索"
                ],
                "summary": "知识库搜索",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.ForestSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.ForestSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.ForestSearchDoc": {
            "post": {
                "description": "知识库搜索文档类型",
                "tags": [
                    "知识库搜索"
                ],
                "summary": "知识库搜索文档类型",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.ForestSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.ForestSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.ForestSearchImage": {
            "post": {
                "description": "知识库搜索图片类型",
                "tags": [
                    "知识库搜索"
                ],
                "summary": "知识库搜索图片类型",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.ForestSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.ForestSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.ForestSearchVideo": {
            "post": {
                "description": "知识库搜索视频类型",
                "tags": [
                    "知识库搜索"
                ],
                "summary": "知识库搜索视频类型",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.ForestSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.ForestSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.GetChunkByID": {
            "post": {
                "description": "根据id获取分片",
                "tags": [
                    "chunk 管理"
                ],
                "summary": "根据id获取分片",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chunkctl.GetChunkByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/chunkctl.GetChunkByIDResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.GetChunkBySequence": {
            "post": {
                "description": "根据序列获取分片",
                "tags": [
                    "chunk 管理"
                ],
                "summary": "根据序列获取分片",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtochunk.GetChunkBySequenceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/dtochunk.GetChunkBySequenceResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.GetChunkDetail": {
            "post": {
                "description": "根据序列获取分片详情（包含文件信息）",
                "tags": [
                    "chunk 管理"
                ],
                "summary": "根据序列获取分片详情",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtochunk.GetChunkBySequenceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/dtochunk.GetChunkDetailResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.GlobalSearch": {
            "post": {
                "description": "全局搜索",
                "tags": [
                    "全局搜索"
                ],
                "summary": "全局搜索",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.GlobalSearchAgent": {
            "post": {
                "description": "全局搜索智能体类型",
                "tags": [
                    "全局搜索"
                ],
                "summary": "全局搜索智能体类型",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.GlobalSearchDoc": {
            "post": {
                "description": "全局搜索文档类型",
                "tags": [
                    "全局搜索"
                ],
                "summary": "全局搜索文档类型",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.GlobalSearchExternalData": {
            "post": {
                "description": "全局搜索外部数据源",
                "tags": [
                    "全局搜索"
                ],
                "summary": "全局搜索外部数据源",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.GlobalSearchForest": {
            "post": {
                "description": "全局搜索知识库",
                "tags": [
                    "全局搜索"
                ],
                "summary": "全局搜索知识库",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.GlobalSearchImage": {
            "post": {
                "description": "全局搜索图片类型",
                "tags": [
                    "全局搜索"
                ],
                "summary": "全局搜索图片类型",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.GlobalSearchVideo": {
            "post": {
                "description": "全局搜索视频类型",
                "tags": [
                    "全局搜索"
                ],
                "summary": "全局搜索视频类型",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/globalsearchctl.GlobalSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.KnowledgeSearch": {
            "post": {
                "description": "知识库搜索文档类型",
                "tags": [
                    "知识库搜索"
                ],
                "summary": "知识库搜索文档类型",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/coze.KnowledgeSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/coze.ForestSearchResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.ListFileChunk": {
            "post": {
                "description": "获取文件chunk",
                "tags": [
                    "chunk 管理"
                ],
                "summary": "获取文件chunk",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chunkctl.ListFileChunkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/chunkctl.ListFileChunkResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.MigrateChunkFileName": {
            "post": {
                "description": "迁移chunk文件名数据",
                "tags": [
                    "chunk 管理"
                ],
                "summary": "迁移chunk文件名数据",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chunkctl.MigrateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/chunkctl.MigrateResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.RerankSearchChunk": {
            "post": {
                "description": "知识库检索rerank版本",
                "tags": [
                    "知识库检索"
                ],
                "summary": "知识库检索rerank版本",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoreranksearch.RerankSearchChunkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response",
                        "schema": {
                            "$ref": "#/definitions/dtoreranksearch.RerankSearchChunkResponse"
                        }
                    }
                }
            }
        },
        "/kesearch.UpdateChunk": {
            "post": {
                "description": "修改chunk",
                "tags": [
                    "chunk 管理"
                ],
                "summary": "修改chunk",
                "parameters": [
                    {
                        "description": "入参",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chunkctl.UpdateChunkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回值",
                        "schema": {
                            "$ref": "#/definitions/chunkctl.UpdateChunkResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "chattype.DataSourceType": {
            "type": "string",
            "enum": [
                "DC"
            ],
            "x-enum-varnames": [
                "DataSourceTypeDC"
            ]
        },
        "chattype.QueryReference": {
            "type": "object",
            "properties": {
                "abstract": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string"
                },
                "chunk_list": {
                    "description": "ChatReferenceChunk ` + "`" + `json:\",inline\"` + "`" + `",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chattype.QueryReferenceChunk"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "data_source": {
                    "description": "DataSourceType 数据源类型 DC",
                    "allOf": [
                        {
                            "$ref": "#/definitions/chattype.DataSourceType"
                        }
                    ]
                },
                "file_id": {
                    "type": "integer"
                },
                "file_name": {
                    "type": "string"
                },
                "forest_id": {
                    "type": "integer"
                },
                "uin": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "chattype.QueryReferenceChunk": {
            "type": "object",
            "properties": {
                "chunk_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "location": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "score": {
                    "type": "number"
                },
                "sequence": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "chunk.Chunk": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string"
                },
                "_score": {
                    "type": "number"
                },
                "_source": {
                    "$ref": "#/definitions/chunk.ChunkInfo"
                }
            }
        },
        "chunk.ChunkInfo": {
            "type": "object",
            "properties": {
                "chunk_size": {
                    "description": "分块的大小",
                    "type": "integer"
                },
                "company_id": {
                    "description": "公司ID",
                    "type": "integer"
                },
                "description": {
                    "description": "分块的描述信息",
                    "type": "string"
                },
                "description_hash": {
                    "description": "分块的描述信息hash",
                    "type": "string"
                },
                "embedding": {
                    "description": "分块的向量表示",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "file_id": {
                    "type": "integer"
                },
                "forest_id": {
                    "description": "ID        string ` + "`" + `json:\"-\"` + "`" + `          // 分块ID",
                    "type": "integer"
                },
                "formula": {
                    "description": "分块的公式",
                    "type": "string"
                },
                "image_embedding": {
                    "description": "图片向量表示",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "image_url": {
                    "description": "分块的图片URL",
                    "type": "string"
                },
                "is_disable": {
                    "description": "是否禁用",
                    "type": "boolean"
                },
                "level": {
                    "description": "分块的层级",
                    "type": "integer"
                },
                "location": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "sequence": {
                    "description": "分块在文件中的顺序",
                    "type": "integer"
                },
                "table": {
                    "description": "分块所属的表格，JSON格式",
                    "type": "string"
                },
                "title_level": {
                    "description": "标题层级",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title_level_ids": {
                    "description": "标题层级ID",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tokens": {
                    "description": "分块的token数量",
                    "type": "integer"
                },
                "type": {
                    "description": "分块类型，例如 \"chunk\", \"entity\", \"relationship\" 等",
                    "type": "string"
                },
                "uin": {
                    "description": "用户ID",
                    "type": "integer"
                },
                "yg_location": {
                    "description": "新位置",
                    "type": "string"
                }
            }
        },
        "chunkctl.DeleteChunkRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "chunk_id": {
                            "type": "string"
                        },
                        "file_id": {
                            "type": "integer"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "chunkctl.DeleteChunkResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object"
                }
            }
        },
        "chunkctl.DisableFileChunkRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "file_id": {
                            "type": "integer"
                        },
                        "is_disable": {
                            "type": "boolean"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "chunkctl.DisableFileChunkResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object"
                }
            }
        },
        "chunkctl.GetChunkByIDRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "chunk_id": {
                            "type": "string"
                        },
                        "file_id": {
                            "type": "integer"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "chunkctl.GetChunkByIDResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "chunk": {
                            "$ref": "#/definitions/chunk.Chunk"
                        }
                    }
                }
            }
        },
        "chunkctl.ListFileChunkRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "file_id": {
                            "type": "integer"
                        },
                        "forest_id": {
                            "type": "integer"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "chunkctl.ListFileChunkResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "chunks": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/chunk.Chunk"
                            }
                        }
                    }
                }
            }
        },
        "chunkctl.MigrateRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "key": {
                            "type": "string"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "chunkctl.MigrateResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object"
                }
            }
        },
        "chunkctl.UpdateChunkRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "chunk_id": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "file_id": {
                            "type": "integer"
                        },
                        "table": {
                            "type": "string"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "chunkctl.UpdateChunkResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "chunk": {
                            "$ref": "#/definitions/chunk.Chunk"
                        }
                    }
                }
            }
        },
        "confluence.SearchResult": {
            "type": "object",
            "properties": {
                "entityType": {
                    "description": "搜索结果类型",
                    "type": "string"
                },
                "excerpt": {
                    "description": "匹配摘要",
                    "type": "string"
                },
                "friendlyLastModified": {
                    "description": "人性化修改时间",
                    "type": "string"
                },
                "id": {
                    "description": "页面ID",
                    "type": "string"
                },
                "lastModified": {
                    "description": "Space                     *Space    ` + "`" + `json:\"space,omitempty\"` + "`" + `                   // 页面所属空间",
                    "type": "string"
                },
                "resultGlobalContainerName": {
                    "description": "全局容器名称（空间名称）",
                    "type": "string"
                },
                "resultGlobalContainerURL": {
                    "description": "全局容器URL",
                    "type": "string"
                },
                "resultParentContainerName": {
                    "description": "父容器名称",
                    "type": "string"
                },
                "resultParentContainerURL": {
                    "description": "父容器URL",
                    "type": "string"
                },
                "score": {
                    "description": "搜索匹配评分",
                    "type": "number"
                },
                "status": {
                    "description": "页面状态，如 \"current\"",
                    "type": "string"
                },
                "title": {
                    "description": "页面标题",
                    "type": "string"
                },
                "type": {
                    "description": "内容类型，如 \"page\"",
                    "type": "string"
                },
                "webLink": {
                    "description": "浏览器访问链接",
                    "type": "string"
                }
            }
        },
        "confluence.SearchResults": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/confluence.SearchResult"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "coze.ForestSearchResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "doc_search_result": {
                            "description": "文档搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchFileType"
                            }
                        },
                        "image_search_result": {
                            "description": "图片搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchFileType"
                            }
                        },
                        "video_search_result": {
                            "description": "视频搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchFileType"
                            }
                        }
                    }
                }
            }
        },
        "coze.KnowledgeSearchRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "forest_id": {
                            "type": "integer"
                        },
                        "is_semantics": {
                            "description": "是否语义搜索",
                            "type": "boolean"
                        },
                        "text": {
                            "type": "string"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dtochunk.GetChunkBySequenceRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "chunk_sequence": {
                            "type": "integer"
                        },
                        "file_id": {
                            "type": "integer"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dtochunk.GetChunkBySequenceResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "chunk": {
                            "$ref": "#/definitions/chunk.Chunk"
                        }
                    }
                }
            }
        },
        "dtochunk.GetChunkDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "detail": {
                            "$ref": "#/definitions/chattype.QueryReference"
                        }
                    }
                }
            }
        },
        "dtoreranksearch.RerankSearchChunkEmbedRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/reranksearch.SearchConfig"
                },
                "file_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "forest_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "question": {
                    "type": "string"
                }
            }
        },
        "dtoreranksearch.RerankSearchChunkEmbedResponse": {
            "type": "object",
            "properties": {
                "search_result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chattype.QueryReference"
                    }
                }
            }
        },
        "dtoreranksearch.RerankSearchChunkRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "$ref": "#/definitions/dtoreranksearch.RerankSearchChunkEmbedRequest"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dtoreranksearch.RerankSearchChunkResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "$ref": "#/definitions/dtoreranksearch.RerankSearchChunkEmbedResponse"
                }
            }
        },
        "github_com_insmtx_corekg_pkgs_einotools_gmail.Message": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gmail.Attachment"
                    }
                },
                "data": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "internalDate": {
                    "type": "string"
                },
                "labelIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "snippet": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "threadId": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "webLink": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_corekg_pkgs_einotools_slack.File": {
            "type": "object",
            "properties": {
                "Username": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "filetype": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "internalDate": {
                    "type": "string"
                },
                "is_public": {
                    "type": "boolean"
                },
                "mimetype": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pretty_type": {
                    "type": "string"
                },
                "preview": {
                    "type": "string"
                },
                "preview_highlight": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "thumb_360": {
                    "type": "string"
                },
                "thumb_360_gif": {
                    "type": "string"
                },
                "thumb_360_h": {
                    "type": "integer"
                },
                "thumb_360_w": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "webLink": {
                    "type": "string"
                },
                "webLinkPublic": {
                    "type": "string"
                }
            }
        },
        "github_com_insmtx_corekg_pkgs_einotools_slack.Message": {
            "type": "object",
            "properties": {
                "Username": {
                    "type": "string"
                },
                "channelId": {
                    "type": "string"
                },
                "channelName": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "internalDate": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "webLink": {
                    "type": "string"
                },
                "webLinkPublic": {
                    "type": "string"
                }
            }
        },
        "globalsearch.HighlightChunk": {
            "type": "object",
            "properties": {
                "_score": {
                    "description": "高亮字段",
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "highlighted_description": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "location": {
                    "description": "位置",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "globalsearch.SearchAgentType": {
            "type": "object",
            "properties": {
                "agent_name": {
                    "type": "string"
                },
                "agent_type": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "highlighted_agent_name": {
                    "description": "高亮字段",
                    "type": "string"
                },
                "highlighted_description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "uin": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "globalsearch.SearchExternalDataType": {
            "type": "object",
            "properties": {
                "confluence_search": {
                    "$ref": "#/definitions/confluence.SearchResults"
                },
                "gmail_drive_search": {
                    "$ref": "#/definitions/googledrive.SearchResult"
                },
                "gmail_search": {
                    "$ref": "#/definitions/gmail.SearchResult"
                },
                "slack_search": {
                    "$ref": "#/definitions/slack.SearchResultOut"
                }
            }
        },
        "globalsearch.SearchFileType": {
            "type": "object",
            "properties": {
                "_score": {
                    "type": "number"
                },
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "forest_id": {
                    "type": "integer"
                },
                "highlighted_file_name": {
                    "type": "string"
                },
                "highlights": {
                    "description": "高亮字段",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/globalsearch.HighlightChunk"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "is_collect": {
                    "type": "boolean"
                },
                "is_like": {
                    "type": "boolean"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "globalsearch.SearchForestType": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "data_source_subtype": {
                    "type": "string"
                },
                "data_source_type": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "forest_name": {
                    "type": "string"
                },
                "forest_type": {
                    "type": "string"
                },
                "highlighted_description": {
                    "type": "string"
                },
                "highlighted_forest_name": {
                    "description": "高亮字段",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "uin": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "globalsearchctl.ForestSearchRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "forest_id": {
                            "type": "integer"
                        },
                        "image_url": {
                            "type": "string"
                        },
                        "is_semantics": {
                            "description": "是否语义搜索",
                            "type": "boolean"
                        },
                        "text": {
                            "type": "string"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "globalsearchctl.ForestSearchResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "doc_search_result": {
                            "description": "文档搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchFileType"
                            }
                        },
                        "image_search_result": {
                            "description": "图片搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchFileType"
                            }
                        },
                        "video_search_result": {
                            "description": "视频搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchFileType"
                            }
                        }
                    }
                }
            }
        },
        "globalsearchctl.GlobalSearchRequest": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "request": {
                    "type": "object",
                    "properties": {
                        "image_url": {
                            "type": "string"
                        },
                        "is_semantics": {
                            "description": "是否语义搜索",
                            "type": "boolean"
                        },
                        "text": {
                            "type": "string"
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "globalsearchctl.GlobalSearchResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "env": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "response": {
                    "type": "object",
                    "properties": {
                        "agent_search_result": {
                            "description": "智能体搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchAgentType"
                            }
                        },
                        "doc_search_result": {
                            "description": "文档搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchFileType"
                            }
                        },
                        "external_search_result": {
                            "description": "外部数据源搜索结果",
                            "allOf": [
                                {
                                    "$ref": "#/definitions/globalsearch.SearchExternalDataType"
                                }
                            ]
                        },
                        "forest_search_result": {
                            "description": "知识森林搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchForestType"
                            }
                        },
                        "image_search_result": {
                            "description": "图片搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchFileType"
                            }
                        },
                        "video_search_result": {
                            "description": "视频搜索结果",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/globalsearch.SearchFileType"
                            }
                        }
                    }
                }
            }
        },
        "gmail.Attachment": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "gmail.SearchResult": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_insmtx_corekg_pkgs_einotools_gmail.Message"
                    }
                },
                "resultSizeEstimate": {
                    "type": "integer"
                }
            }
        },
        "googledrive.FileInfo": {
            "type": "object",
            "properties": {
                "createdTime": {
                    "type": "string"
                },
                "hasThumbnail": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                },
                "modifiedTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owners": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "parentTds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "shared": {
                    "type": "boolean"
                },
                "size": {
                    "type": "integer"
                },
                "thumbnailLink": {
                    "type": "string"
                },
                "trashed": {
                    "type": "boolean"
                },
                "webContentLink": {
                    "type": "string"
                },
                "webLink": {
                    "type": "string"
                }
            }
        },
        "googledrive.SearchResult": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/googledrive.FileInfo"
                    }
                }
            }
        },
        "reranksearch.SearchConfig": {
            "type": "object",
            "properties": {
                "description_weight": {
                    "description": "chunk权重",
                    "type": "number"
                },
                "embedding_weight": {
                    "description": "embedding权重",
                    "type": "number"
                },
                "enabel_abstract": {
                    "description": "是否需要摘要",
                    "type": "boolean"
                },
                "enable_rerank": {
                    "description": "是否需要rerank",
                    "type": "boolean"
                },
                "fall_back_to_topk": {
                    "description": "如果第一次 rerank 过滤后为空，则直接取 topk 返回",
                    "type": "boolean"
                },
                "fetch_factor": {
                    "description": "第一次检索 topn*fetch_factor的chunk",
                    "type": "integer"
                },
                "neighbor_size": {
                    "description": "邻居chunk数量",
                    "type": "integer"
                },
                "rerank_threshold": {
                    "description": "rerank 过滤阈值",
                    "type": "number"
                },
                "topk": {
                    "description": "每次rerank后，如果使用过滤阈值，若无chunk，则默认提取前topk个",
                    "type": "integer"
                },
                "topm": {
                    "description": "整个检索过程最多返召回的chunk数量",
                    "type": "integer"
                },
                "topn": {
                    "description": "每次rerank后保留的chunk数量",
                    "type": "integer"
                }
            }
        },
        "slack.Files": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_insmtx_corekg_pkgs_einotools_slack.File"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "slack.Messages": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_insmtx_corekg_pkgs_einotools_slack.Message"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "slack.SearchResultOut": {
            "type": "object",
            "properties": {
                "files": {
                    "$ref": "#/definitions/slack.Files"
                },
                "messages": {
                    "$ref": "#/definitions/slack.Messages"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Description for what is this security definition being used",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfokesearch holds exported Swagger Info so clients can modify it
var SwaggerInfokesearch = &swag.Spec{
	Version:          "",
	Host:             "47.92.112.152:8199",
	BasePath:         "/apis/p",
	Schemes:          []string{"http"},
	Title:            "kesearch API````````````",
	Description:      "doc.json",
	InfoInstanceName: "kesearch",
	SwaggerTemplate:  docTemplatekesearch,
}

func init() {
	swag.Register(SwaggerInfokesearch.InstanceName(), SwaggerInfokesearch)
}
