FROM node:20-alpine AS building

WORKDIR /app
ADD . /app

ENV NODE_OPTIONS="--max-old-space-size=4096"

RUN pnpm install
RUN pnpm run build:prod

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=building /app/dist/ /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
